# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMainWindow(object):
    def setupUi(self, frmMainWindow):
        frmMainWindow.setObjectName(_fromUtf8("frmMainWindow"))
        frmMainWindow.resize(800, 480)
        frmMainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtGui.QWidget(frmMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(620, 480, 131, 41))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 380, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.btnOff = QtGui.QPushButton(self.centralwidget)
        self.btnOff.setGeometry(QtCore.QRect(500, 430, 131, 41))
        self.btnOff.setObjectName(_fromUtf8("btnOff"))
        self.btnRead = QtGui.QPushButton(self.centralwidget)
        self.btnRead.setGeometry(QtCore.QRect(650, 430, 131, 41))
        self.btnRead.setObjectName(_fromUtf8("btnRead"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(500, 130, 291, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.numLimit = QtGui.QSpinBox(self.centralwidget)
        self.numLimit.setGeometry(QtCore.QRect(700, 370, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.numLimit.setFont(font)
        self.numLimit.setMinimum(2)
        self.numLimit.setMaximum(200)
        self.numLimit.setObjectName(_fromUtf8("numLimit"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 150, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lblSpeed = QtGui.QLabel(self.centralwidget)
        self.lblSpeed.setGeometry(QtCore.QRect(530, 190, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblSpeed.setFont(font)
        self.lblSpeed.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);"))
        self.lblSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSpeed.setObjectName(_fromUtf8("lblSpeed"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(500, 230, 291, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 330, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lblDetection = QtGui.QLabel(self.centralwidget)
        self.lblDetection.setGeometry(QtCore.QRect(600, 290, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblDetection.setFont(font)
        self.lblDetection.setObjectName(_fromUtf8("lblDetection"))
        self.lblAccurcy = QtGui.QLabel(self.centralwidget)
        self.lblAccurcy.setGeometry(QtCore.QRect(600, 330, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblAccurcy.setFont(font)
        self.lblAccurcy.setObjectName(_fromUtf8("lblAccurcy"))
        self.lblNumber = QtGui.QLabel(self.centralwidget)
        self.lblNumber.setGeometry(QtCore.QRect(10, 380, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.lblNumber.setFont(font)
        self.lblNumber.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.lblNumber.setFrameShape(QtGui.QFrame.Box)
        self.lblNumber.setText(_fromUtf8(""))
        self.lblNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNumber.setObjectName(_fromUtf8("lblNumber"))
        self.lblImg = QtGui.QLabel(self.centralwidget)
        self.lblImg.setGeometry(QtCore.QRect(10, 10, 471, 361))
        self.lblImg.setFrameShape(QtGui.QFrame.Box)
        self.lblImg.setText(_fromUtf8(""))
        self.lblImg.setScaledContents(True)
        self.lblImg.setObjectName(_fromUtf8("lblImg"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lblStatus = QtGui.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(590, 100, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lblStatus.setFont(font)
        self.lblStatus.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);"))
        self.lblStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(500, 80, 291, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        frmMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmMainWindow)
        QtCore.QMetaObject.connectSlotsByName(frmMainWindow)

    def retranslateUi(self, frmMainWindow):
        frmMainWindow.setWindowTitle(_translate("frmMainWindow", "Vehicle Number Plate Recodnition System", None))
        self.pushButton.setText(_translate("frmMainWindow", "Start", None))
        self.label.setText(_translate("frmMainWindow", "Speed Limit (km/h)", None))
        self.btnOff.setText(_translate("frmMainWindow", "Shutdown", None))
        self.btnRead.setText(_translate("frmMainWindow", "Read Plate", None))
        self.label_2.setText(_translate("frmMainWindow", "Current Speed", None))
        self.lblSpeed.setText(_translate("frmMainWindow", " 0 Km/h", None))
        self.label_3.setText(_translate("frmMainWindow", "Number plate detection", None))
        self.label_4.setText(_translate("frmMainWindow", "Detected :", None))
        self.label_5.setText(_translate("frmMainWindow", "Accuracy :", None))
        self.lblDetection.setText(_translate("frmMainWindow", "-", None))
        self.lblAccurcy.setText(_translate("frmMainWindow", "-", None))
        self.label_6.setText(_translate("frmMainWindow", "Status :", None))
        self.lblStatus.setText(_translate("frmMainWindow", "Monitoring", None))
        self.label_7.setText(_translate("frmMainWindow", "<html><head/><body><p align=\"center\">Vehicle Number Plate Recognition </p><p align=\"center\">System</p></body></html>", None))

